### ISSUE TITLE
Playlist Loader, SMB URL, only last channel work

### ISSUE THREAD

**Issue by WAWAN75** [avigdork/xbmc-avigdork#2]
Hello,

I'm using SPMC on a NVIDIA Shield TV box (Android). I want to use playlist loader to be able to open further m3u playlists. All my videos are on a NAS server.

My playlist look like:

#EXTM3U
#EXTINF:-1 tvg-id="id1" tvg-name="Transas" tvg-logo="ecdis-screen2.jpg",Transas
smb://ServeurOffice/Divers/video Infos nav and CCTV/Transas.mp4
#EXTINF:-1 tvg-id="id2" tvg-name="SONAR" tvg-logo="SONAR.jpg",Sonar
smb://ServeurOffice/Divers/video Infos nav and CCTV/Sonar.mp4
#EXTINF:-1 tvg-id="id3" tvg-name="Transas" tvg-logo="ecdis-screen2.jpg",Transas
smb://ServeurOffice/Divers/video Infos nav and CCTV/Transas.mp4

Only the last item (id3) is working. None of the first and second are working. Example : If I copy/paste the 2nd item at the end, this channel (id2) will work but no more id3. Only the last channel work....
When I try with my Windows laptop using VLC or Kodi Jarvis 16.1, this playlist is working well...

I've also try to use Kodi 17 on the Nvidia, same issue.

Any ideas ? 

Thanks in advance.

**Comment by avigdork** [comment]
Hi.
Please check ver 1.1.8.

**Comment by WAWAN75** [comment]
Hi,

Work great ! 

Thanks !
