### ISSUE TITLE
Playlist loader לא עובד טוב

### ISSUE THREAD

**Issue by kodibp** [avigdork/xbmc-avigdork#7]
היי

חלק מההרחבה לא פעיל...אשמח שתתקן

אני אוהב אץ מה שעשית בערוצי מוזיקה 2

רק שזה גם לא פעיל 😞

בברכה kbp

**Comment by avigdork** [comment]
@kodibp
מה זה אומר לא פעיל?
ההרחבה מגיעה ללא רשימות, כל משתמש מוסיף רשימות משל עצמו. 
ההרחבה מציגה את הערוצים, אם ערוץ מסויים לא עובד זה קשור כבר למי שיצר את הרשימה.

**Comment by kodibp** [comment]
ערוצי מוזיקה 2 לא מציג כלום...בעבר היה ניכנס לרשימה של תחנות...לדוגמה

בתאריך יום ג׳, 3 ביול' 2018, 21:57, מאת Avigdor ‏<notifications@github.com>:

**Comment by avigdork** [comment]
@kodibp
כמו שכתבתי לך מקודם, זאת לא בעיה בהרחבה. 
זאת בעיה במקורות הערוצים שהפסיקו לעבוד. תברר את זה מול יוצר הרשימה מוזיקה 2.

**Comment by avigdork** [comment]
@kodibp 
אין לי מושג.

**Comment by kodibp** [comment]
Ok...הייתי בטוח שאתה אחראי על הקישורים בהרחבות...

נמתין שיתקן

יש עוד אחד שלא פותח כלום....

לפי הבנתי ההרחבה שלך זה פלייליסטים של אנשים??

**Comment by avigdork** [comment]
@kodibp 
ההרחבה שלי נוצרה כדי לתת אפשרות לעבוד עם כמה רשימות ולהשתמש ברשימת מועדפים.
זאת רק הפלטפורמה.
